### ISSUE TITLE
Stackblitz edit link

### ISSUE THREAD

**Issue by AndreasKrestan** [rstropek-teaching/turmrechnen-quiz-4ahif-AndreasKrestan#1]
https://stackblitz.com/edit/angular-9xqbgq

Here is my solution to the Turmrechnungs example,
the styling is a mess but I hope you can cope with it.
Thank you for taking a look at it and have a good day.

Andreas Krestan

**Comment by rstropek** [comment]
Well done, your extra point is secured.

Greetings,
Rainer Stropek.
